### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/Contacts#1]
We need some sort of logging for the future. That could happen in a channel thats not accessible to the general public.

The bot should:

- Write all deleted messages into the channel
- Write a small report on who was muted for which amount of time including a small chatlog
- Maybe just telling who joined and leaved? 

Ideas appreciated

**Comment by ObsidianMinor** [comment]
For deleted messages, I might be able to find who deleted the message

**Comment by mastorm** [comment]
Thats a good one

**Comment by deccer** [comment]
just log to #stafflog

- equally looking patterns for actions (ban/kick/mute/delete)
  "UserX kicked/banned/muted/deleted UserY"
  UserX has to manually provide a proof of misbehaviour either before or after into #stafflog

- no join/leave logging - gets obnoxious with many people on the server (seen this even on very small (40ppl) servers

**Comment by mastorm** [comment]
@deccer well, as its stated above, this logging stuff will not reach general public. Growth is something that i personally care about alout

**Comment by deccer** [comment]
@mastorm sure, but you 
1) don't count joins and leaves (grouped by user#id) 
2) don't pull statistics about growth from that.
3) you as a server admin can see how many people are there online and offline

least scenario I can see is, let the bot just count, nobody needs to see the joins/leaves - but that would be even yet another issue, I reckon. Something about available commands.

**Comment by mastorm** [comment]
So you want to protect me from getting frustrated about leaves? :D

**Comment by jmazouri** [comment]
It may be more viable to store the messages for retrieval later, instead of dumping everything into the log channel automatically.

Then you could create a log query command, something like `/log 11/20/2016 to 11/25/2016` to get data for the week or `/log 30 minutes` for the last half hour. You could potentially implement keyword search of messages, filter by user, event type, etc, as well.

**Comment by mastorm** [comment]
well, if we have data storage, ^this

**Comment by MarkusG** [comment]
@ObsidianMinor unfortunately the Discord API doesn't give _who_ deleted the message. Only who's message it was.

**Comment by ObsidianMinor** [comment]
welp there goes my master plan

**Comment by ObsidianMinor** [comment]
Logging been added
