### ISSUE TITLE
[FEATURE] Evaluation commands

### ISSUE THREAD

**Issue by khionu** [discord-csharp/Contacts#14]
I suggest adding two eval commands, one that is public and one that is not. The non-public can be used for grabbing data that is not easily grabbed, otherwise, and the public can be used for checking code.

The Roslyn Scripting API is recommended.
https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples

**Comment by MarkusG** [comment]
I think Jimmacle has done a little work on this. See #5.

**Comment by ObsidianMinor** [comment]
Probably duplicate of #5
