### ISSUE TITLE
[FEATURE] .NET Reference Source

### ISSUE THREAD

**Issue by markusamshove** [discord-csharp/Contacts#15]
It would be nice to have a command similar to the ~msdn command for getting a link to the Referencesource.

# Command

    ~source <searchterm>

# Result

A link to the Referencesource

# Example

    ~source StringBuilderCache
    Contacts: https://referencesource.microsoft.com/#mscorlib/system/text/stringbuildercache.cs,a6dbe82674916ac0

    ~source String.Trim
    Contacts: https://referencesource.microsoft.com/#mscorlib/system/string.cs,06a5f7c688e69307

It should most likely get the first fitting result from the query.

It should also determine what you're looking for based on the naming conventions of C#.

* If the searchterm contains a . return the first method.
* If the searchterm starts with a capital letter return the first class.
* If there is nothing found based on naming convention, return the first result. Example:

    (it's a field)
    ~source Int32.MaxValue
    Contacts: https://referencesource.microsoft.com/#mscorlib/system/int32.cs,c45153c0501d7122

# Implementation

I haven't found any hint if there is a API to query the Referencesource, so it might need to parse raw html.

**Comment by ObsidianMinor** [comment]
Done in #20
