### ISSUE TITLE
[FEATURE] MOTD for new users in a channel

### ISSUE THREAD

**Issue by Insire** [discord-csharp/Contacts#4]
As a user i'd like to be able to automatically message new users with a MOTD
- message should be private
- message should be configurable by a user with a certain role on the server
- message should have its own command: maybe -motd (content)
- message should be able to contain links

**Comment by MarkusG** [comment]
To clarify, do you mean a command that a user can execute that sends a predetermined message to another user, or something that is sent to a user that has just joined the server?

**Comment by Insire** [comment]
I mean a message thats send automatically when they enter the server. But having it available as command would be nice too.
