### ISSUE TITLE
[FEATURE] Recallable memos

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/Contacts#8]
The ability to create and edit "memos", which can be saved as keywords and recalled. Effectively the same as the "ahh" bot from the Discord.Net channel.

Potentially also keep track of how often each memo is recalled, and use that to fuzzy-match keywords as well.

**Comment by khionu** [comment]
I would recommend not doing fuzzy matching, unless, like R. Danny, you do it to provide suggestions if no match is found. Fuzzy matching can get quite weird, and I don't see it having much use unless for this.

Maybe do keyword searches for where the Levenshtein Distance is less than 2 or 3?

**Comment by jmazouri** [comment]
Right, it'd be to provide a list of options in case you make a typo / it can't find what keywork you're looking for. There's a number of implementations of it in this library, which could be tested for our specific use case.

https://fuzzystring.codeplex.com/

**Comment by ObsidianMinor** [comment]
Did done do
